### PR TITLE
add me

### PR DESCRIPTION
**Pull request by ankita132**

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
You need to make changes in `index.html` and not `Readme.md` so that it reflects on the website otherwise it will just show on our github repo. See this PR ( #48 ) to see how to do it!

**Comment by ankita132** [comment]
changed the index.html

**Comment by pranitbauva1997** [comment]
Nice. Now you need to squash all of these commits into one.

Use `git rebase -i HEAD~4`

**Comment by ankita132** [comment]
did that..sorry for this incovenience.This was the first time for me.I will take care next time.

**Comment by pranitbauva1997** [comment]
Don't worry. Everybody does mistakes their first time. Even I did.

**Pull request merged**
