### PR TITLE
Adding profile details for Vishesh Agarwal

### PR DESCRIPTION
**Pull request by TheGrayFrost**

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
There are 4 commits, where this is only one logical change.

Please squash all the commits.

Hint: `git rebase -i HEAD~4`

**Comment by pranitbauva1997** [comment]
You still have five commits while only one is required.

**Comment by americast** [comment]
@TheGrayFrost Please remove the files unrelated to this website. Only two files should be edited. :slightly_smiling_face:

**Comment by TheGrayFrost** [comment]
Sorry for the delay. Actually, I had gone home for Holi and was travelling.
I have just returned to Kgp. I'll do the work asap.

**Comment by TheGrayFrost** [comment]
Sorry for the delay. Actually, I had gone home for Holi and was travelling.
I have just returned to Kgp. I'll do the work asap.

>

**Pull request closed without merging**
