### PR TITLE
Add Rajdeep Choudhury

### PR DESCRIPTION
**Pull request by RajdeepC98**
add Rajdeep Choudhury

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
Can you squash all the commits together?

Hint: `git rebase -i HEAD~4`

**Comment by RajdeepC98** [comment]
used git rebase but still seeing multiple commits in PR

**Comment by americast** [comment]
@RajdeepC98 You have made six commits, you need to squash them into one (the first one). So use `git rebase -i HEAD~6` and replace `pick` with `squash` for the last five commits. This means the commits you have termed as "squash" will get get removed and get combined into the last "non-squashed" commit. After this, you will also be prompted to rename the last commit according to your wish. Next, you need to "force push" it to Github as you are changing history. Use `git push origin add_me --force` where "addme" is the name of the branch from which you are sending the PR and "origin" is the remote stream. Hope it helps... :smile:

**Comment by RajdeepC98** [comment]
i deleted the index.html~ file. but still conflicts need to be resolved. cant do it :(

**Comment by americast** [comment]
@RajdeepC98 The image you uploaded need to be scaled to 200x200
In order to resolve conflicts, first update your master branch so that it's commit history matches with that of the upstream. You may take help from here: https://github.com/kaustubhhiware/Git_Learning/blob/master/syncing_with_original_repo.txt
Now, checkout to the branch where you were editing and try to merge master with it using `git merge master`. This will lead to merge conflicts. Resolve the conflicts locally in the mentioned files. Then, push the temporary branch to Github.
You may consult @pranitbauva1997 before proceeding. He may be able to throw some more light on the issue.

**Comment by pranitbauva1997** [comment]
@americast It is often advisable not to use `git merge master` in such situations. In such things, you should first update your `master` with the `upstream`, `checkout` the branch you are working on and then `rebase` that branch on `master`.

**Comment by pranitbauva1997** [comment]
@RajdeepC98 Don't worry, resolving conflicts is a difficult task. And I will do it for you as of now!

**Comment by RajdeepC98** [comment]
thanks @pranitbauva1997 !

**Pull request merged**
