### PR TITLE
added new member details

### PR DESCRIPTION
**Pull request by basher666**
added new member details

### CODE REVIEW

**Comment by abhinavjain241** [comment]
Hey @swastikhaldar , I guess you created a swap file in the process, i.e index.html~, make sure you remove that file, it's unnecessary. I will merge the PR then.

**Comment by abhinavjain241** [comment]
@swastikhaldar : Please rebase, it looks as if there are conflicts.

**Comment by abhinavjain241** [comment]
@swastikhaldar : There are still conflicts in this, so please remove them.

**Comment by abhinavjain241** [comment]
@swastikhaldar : Still has conflicts. Please rebase and commit.

**Comment by pranitbauva1997** [comment]
Closing this PR due to inactivity. If you want to work on it, feel free to re-open it!

**Pull request closed without merging**
