### PR TITLE
Add Sayan Sinha

### PR DESCRIPTION
**Pull request by americast**
Add Sayan Sinha as a member of the software team.

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
@americast Since there is only "one" logical change it is more appropriate to squash both the commits. Plus please change the photo. I am guessing you don't like to put your personal photo but this is an official site.

Nice efforts though! And this was pretty fast.

**Comment by americast** [comment]
@pranitbauva1997 I had just one commit in the beginning, but after having a look at your comment in pull #55, I decided to switch to two.
It's not that I don't like to put a personal photo, but I don't have one :stuck_out_tongue:

**Comment by pranitbauva1997** [comment]
@americast It is extremely good that you are seeing other PRs to get reference before coding it yourself. Though for that PR there are in total two photos of two different people with the text of only one person. So at that place one member is being added (with text and photo) and one other member's photo is being changed. So those are two different changed.

I guess then it is time to click one :P

**Comment by americast** [comment]
@pranitbauva1997 Squashed it! Due to the absence of proper initial comment, I could not understand the reason behind two commits (and it still looks pretty amusing that someone would change someone else's pic in a commit :stuck_out_tongue:).

**Pull request merged**
