### PR TITLE
added my info

### PR DESCRIPTION
**Pull request by rishikraj**

### CODE REVIEW

**Comment by americast** [comment]
@rishikraj Please crop the image and make it 200x200.

Gramercy...

**Comment by pranitbauva1997** [comment]
And please make one commit for one logical change

**Comment by americast** [comment]
@pranitbauva1997 I guess @rishikraj is not using Git. He has sent the PR after editing/adding required files on GitHub itself. So, it may be uneasy for him squash commits. How about you "squash-merge" them ?

**Comment by rishikraj** [comment]
I tried it through GIT also but I am facing some error by that method so
after that I used  GITHUB .

**Comment by pranitbauva1997** [comment]
@rishikraj No worries! We are meeting on Monday. Sit back after the meeting with me and we will get this sorted out! :-)

**Comment by rishikraj** [comment]
Ok sure ,bcz  I am not familiar with this git environment so please keep
suggesting .
Thanks

**Comment by pranitbauva1997** [comment]
@rishikraj  Please *refrain* from using chat language and type proper and correct English.

**Pull request closed without merging**
