### PR TITLE
Adding my name in Team List

### PR DESCRIPTION
**Pull request by npochhi**
Added my name and photo.

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
You have also added a swap file which shouldn't be present.

To remove this:
`$ git reset --soft`
`$ git reset HEAD .index.html.swp`
`$ git commit --amend --no-edit`
`$ git push origin nilayaddmember --force`

This should probably do it. If not please ping me on slack.

I think you did `git add *` and this got added so we should probably add `*.swp` to our `.gitignore` file too.

**Comment by npochhi** [comment]
Is it okay now?

**Comment by pranitbauva1997** [comment]
The commit history isn't looking proper. Did you follow the steps I told?

**Comment by npochhi** [comment]
I added the *.swp files to gitignore. And pushed the files.

**Comment by pranitbauva1997** [comment]
@npochhi I guess there was a communication gap between us. I have already added the swp files to gitignore in #66 . Nevertheless, it is pointless stretching this further. I will just merge it!

**Pull request merged**
