### PR TITLE
Content Added. 

### PR DESCRIPTION
**Pull request by abhinavjain241**

### CODE REVIEW

**Comment by sam17** [comment]
Add Khoslas photo.
On first loading of page, the team is not displayed properly. Clicking on all displays it properly though. 

Also, we cannot add images of robots we have not made. Take photos of our robots and put them along with photos from simulator. 
Also add link to PDG's page. 

Write about Research Areas:
1. Coverage
2. Mutual Localisation
2.1. Vision Based 
2.2. Wifi Based
2.3. IR/Sharp Based
3. Multi Agent Path Planning

**Comment by sam17** [comment]
Use the link [1].


[1] - https://drive.google.com/drive/folders/0B0UXcR6jjCx3fnYxdFlIRGhhYXh5MXlaNXFQd0psOE1BcmphZG1OYS1XUGZKc1d0X1hleDA

**Comment by sam17** [comment]
Divyansh + Khosla +Kumar Ankit + Avilash + Barno +Roy Photo. 
Photos I mailed on group.
Content In the Folder.
Video from KK.
Shushman - Alumni (Founder)

**Comment by abhinavjain241** [comment]
#### Updated. 1 new commit.

**Remaining:**
- Photo Carousel / Video from KK
- Content to be added as Bootstrap pills or on a new page
- Shushman - Alumni - *Please give details about this.*

**Comment by sam17** [comment]
I meant, instead of writing Project Founder under Shushman, Write "Alumni (Founder)"

The team pics on opening are still weird. They become proper on clicking All/Software/Embedded.

Content should be a new tab called Project Description and the current one should become "Overview"

**Comment by sam17** [comment]
For video, you can also take a video of your screen yourself as robots patrol in simulator.

**Comment by abhinavjain241** [comment]
Should I link the [wiki](https://github.com/Swarm-IITKgp/wiki) in the *"Project Description Section"* or should I make some vertical buttons (Bootstrap pills) and display content there itself?

**Comment by sam17** [comment]
Content on website and give link to wiki somewhere, instead link to organisation itself.

**Comment by abhinavjain241** [comment]
You can preview the website [here](http://abhinavjain241.github.io/Swarm-IITKgp.github.io). The PR is good from my side to merge now.

**Comment by sam17** [comment]
Awesome!

**Pull request merged**
